name: EXPERIMENTAL ACVP Artifact validation

on:
  push:
    branches: [ 'acvp-auto-testing' ]


jobs:
  acvp_validation:
    runs-on: ubuntu-latest
    # Is this an appropriate dotnet image?
    container: mcr.microsoft.com/dotnet/runtime
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./pqc-certificates
      - name: Checkout ACVP code
        uses: actions/checkout@v4
        with:
          # I would rather clone the official repo usnistgov/ACVP-Server
          # and then have any supporting code here in this pqc-certificates repo.
          repository: josephlukefahr/ACVP-Server
          path: ./ACVP-Server
      - run: mkdir ./output
      - run: /bin/sh ./pqc-certificates/providers/nist-acvts-test/setup_acvts_env.sh ./AVCP-Server
      - run: /bin/sh ./pqc-certificates/src/test_certs_r3_with_acvp.sh ./pqc-certificates ./ACVP-Server

    ## TODO -- This output needs to contain all the <provider>_NIST-ACVP.csv files
    ##         Plus any log files (ideally all in a single log file, if that's possible)
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Compatibility_acvp_csv
          path: ./output/
